### ISSUE TITLE
Sync_environment.py -> Add parameter for projects

### ISSUE THREAD

**Issue by umrubi1** [uyuni-project/contrib#11]
Hi, 

thanks for sharing your useful scripts. 
If possible, could you please implement in "sync_environment.py" the "project"-parameter? It would be useful to update the environment for a dedicated project. Currently the scripts updates all environments with the same label.

Thanks und advance.

**Comment by mbrookhuis** [comment]
I think you should use sync_stage.py. This does what you wants.

**Comment by mbrookhuis** [comment]
I think you should use sync_stage.py. This does what you wants.

**Comment by umrubi1** [comment]
Hi, thanks for your reply. I will try it.
