### ISSUE TITLE
Question: SP-Migration with "system_update.py" using "custom base channels"

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/contrib#3]
I want to use system_update.py 
https://github.com/uyuni-project/contrib/blob/main/uyuni-tools/system_update.py
to do SP-Migrations from 
CLM Project:    sles15_sp2
    ENV:	qa
to
CLM Project:    sles15_sp3
    ENV:	qa

unfortunately it seams that the tool needs vendor channels and no custom channels

uyuni-srv:/opt/susemanager# cat configsm.yaml
SNIP
maintenance:
   wait_between_systems: 2
   exclude_for_patch:
      - lx0001
      - lx0002
   sp_migration_project:
      sl124: sl125
      sles15_sp2: sles15_sp3
   sp_migration:
      sles15-sp2: sles15-sp3
   exception_sp:
      sles15-sp2:
         - lx0003

Question: is there a possibility to run the tool from custom-base-channel (e.g. "sles15_sp2", env: "qa") to custom-base-channel (e.g. "sles15_sp3", env: "qa")

Any hint welcome;

**Comment by mbrookhuis** [comment]
What do you mean with custom-base-channel? If you create a new CLM project, the base channel is already custom. Or did you create a new base channel from "scratch" and not from the product pool channel as it source. If you created you own basechannel it could be that you are missing metadata that is needed to perform an SP Migration.
Is the support pack migration available from within the GUI?

Can you post the error. I will have a look if this can be solved.

**Comment by mbrookhuis** [comment]
will close as I didn't receive an answer
