### ISSUE TITLE
Include again cve_report.py

### ISSUE THREAD

**Issue by ppfrassino** [uyuni-project/contrib#9]
Please re-include cve_report.py
Thanks 
Pierpa

**Comment by mcalmer** [comment]
@ppfrassino Which tool do you mean? I checked the history and I could not find a tool named like this.

**Comment by mbrookhuis** [comment]
Added cve_report.py back. Waiting for merge.

**Comment by ppfrassino** [comment]
Michael,
this is a good news. Thanks for your support !!!

PIerpa

Da: Michael Brookhuis ***@***.***>
Inviato: martedì 2 novembre 2021 15:01
A: uyuni-project/contrib ***@***.***>
Cc: Pier Paolo Frassino ***@***.***>; Mention ***@***.***>
Oggetto: EXT:Re: [uyuni-project/contrib] Include again cve_report.py (#9)

** CAUTION: Questa mail è stata inviata da un mittente esterno a Solve.It. Presta la massima attenzione nell'apertura di links e tratta con estrema cautela gli eventuali allegati. **

Added cve_report.py back. Waiting for merge.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fuyuni-project%2Fcontrib%2Fissues%2F9%23issuecomment-957639589&data=04%7C01%7Cpierpaolo.frassino%40solve.it%7Cd4cab87270c2481ec3b008d99e093164%7C487ab28c2c8d4ff4828579f5f4227ae4%7C0%7C0%7C637714584598707395%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L9gX%2B80LG%2FnZkPjkq6r21t8MkMvFhLpYEeb2BDw299w%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAV4KXVU7ZB6E4SMFZVQJWCTUJ7VJNANCNFSM5FUMZNQA&data=04%7C01%7Cpierpaolo.frassino%40solve.it%7Cd4cab87270c2481ec3b008d99e093164%7C487ab28c2c8d4ff4828579f5f4227ae4%7C0%7C0%7C637714584598717393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9hkXcQDeWgecA6VJMHgDuLrU3tF8GS4URzIL%2Ba4b3r0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpierpaolo.frassino%40solve.it%7Cd4cab87270c2481ec3b008d99e093164%7C487ab28c2c8d4ff4828579f5f4227ae4%7C0%7C0%7C637714584598727385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FDWsJkkND4evP0tGCc1YYa9dVKUmBLX7BD0UvUAS9mQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpierpaolo.frassino%40solve.it%7Cd4cab87270c2481ec3b008d99e093164%7C487ab28c2c8d4ff4828579f5f4227ae4%7C0%7C0%7C637714584598727385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pqYCU41bG6EOp1F%2FwB5d7E2IJFBeIgUx2NTXpB8q26E%3D&reserved=0>.
